### ISSUE TITLE
An anchor in URL

### ISSUE THREAD

**Issue by vad4msiu** [erichmenge/signed_form#27]
I have a form with anchor:

``` ruby
= simple_form_for resource, url: resource_path(resource, anchor: 'form-update'), html: { id: 'form-update' }, method: 'put' do
...
```

And when I submit it I get an error:

```
SignedForm::Errors::InvalidURL - SignedForm::Errors::InvalidURL:
  signed_form (0.2.0) lib/signed_form/gate_keeper.rb:35:in `verify_destination'
  signed_form (0.2.0) lib/signed_form/gate_keeper.rb:11:in `initialize'
  signed_form (0.2.0) lib/signed_form/action_controller/permit_signed_params.rb:18:in `permit_signed_form_data'
```

I don't know exactly how much it correct but maybe skip a anchor? Like this:

```
    def verify_destination
      return unless options[:method] && options[:url]
      raise Errors::InvalidURL if options[:method].to_s.casecmp(@request.request_method) != 0
      controller_url = @controller.url_for(options[:url])
      url = URI.parse(controller_url).path
      raise Errors::InvalidURL if url != @request.fullpath && url != @request.url
    end
```

**Comment by tubbo** [comment]
Definitely makes sense, because the `#anchor` part of the URL is ignored by the server, but the Rails route helpers still create them in the URLs, which fails the signed_form verify_destination check for basically no reason.

I like your approach @vad4msiu, but not sure if that will catch all instances. For example, this method of checking against just the path of the URL will break if someone were to use a `_url` route helper (which returns a fully-qualified URL), or if you wanted to include parameters that aren't in the route:

```ruby
app.artists_path(id: 1, anchor: 'test') # => "/artists?id=1#test"
app.artists_url(id: 1, anchor: 'test') # => "http://www.example.com/artists?id=1#test"
URI.parse(app.artists_url(id: 1, anchor: 'test')).path # => "/artists"
```

I think simply splitting the String on '#' and returning the left side of the split would be sufficient in getting rid of the anchor:

```ruby
app.artists_url(id: 1, anchor: 'test').split('#').first # => "http://www.example.com/artists?id=1"
```

If no one has an issue with this, I'll submit a PR.

**Comment by vad4msiu** [comment]
:+1:
